### ISSUE TITLE
Error: obj must be an instance or subtype of type

### ISSUE THREAD

**Issue by kapitanluffy** [yaroslavyaroslav/OpenAI-sublime-text#15]
This happens when I do `completions`

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python38\sublime_plugin.py", line 1697, in run_
    return self.run(edit, **args)
  File "C:\Users\lupi\AppData\Roaming\Sublime Text\Installed Packages\OpenAI completion.sublime-package\openai.py", line 48, in run
  File "C:\Users\lupi\AppData\Roaming\Sublime Text\Installed Packages\OpenAI completion.sublime-package\openai_worker.py", line 24, in __init__
TypeError: super(type, obj): obj must be an instance or subtype of type
```

**Comment by yaroslavyaroslav** [comment]
Should be fixed in 2.0.2, unfortunately I don't know a way how to test these kind of fixes locally, so if it still appears, please reopen this issue.
