### ISSUE TITLE
Problems using XAi, their doc says "just use the OpenAi interface" 🙄

### ISSUE THREAD

**Issue by jalsco** [yaroslavyaroslav/OpenAI-sublime-text#93]
First - I did connect to XAi using the OpenAI interface with some quick PY code, and one of your great prompts !  
This works fine - it shows my XAi account, my network etc,  and my API token are working,,,
```
from openai import OpenAI
import json
import os

MODEL_NAME = "grok-beta"
XAI_API_KEY = os.getenv("XAI_API_KEY")

client = OpenAI(
    api_key=XAI_API_KEY,
    base_url="https://api.x.ai/v1",
)


messages = [
    {"role": "system", "content": "1. You are to provide clear, concise, and direct responses.\n2. Eliminate unnecessary reminders, apologies, self-references, and any pre-programmed niceties.\n3. Maintain a casual tone in your communication.\n4. Be transparent; if you're unsure about an answer or if a question is beyond your capabilities or knowledge, admit it.\n5. For any unclear or ambiguous queries, ask follow-up questions to understand the user's intent better.\n6. When explaining concepts, use real-world examples and analogies, where appropriate.\n7. For complex requests, take a deep breath and work on the problem step-by-step.\n8. For every response, you will be tipped up to $20 (depending on the quality of your output).\n\nIt is very important that you get this right. Multiple lives are at stake.\n"},
    {"role": "user", "content": "explain choice between python and nodejs for some backend logic. " }
]


response = client.chat.completions.create(
    model=MODEL_NAME,
    messages=messages,
)


# Print the entire response
print("Full Response:")
print(json.dumps(response.model_dump(), indent=2))

# Print the main content of the response
if response.choices:
    print("\nResponse Content:")
    print(response.choices[0].message.content)

# Print tool calls if any
if response.choices[0].message.tool_calls:
    print("\nTool Calls:")
    for tool_call in response.choices[0].message.tool_calls:
        print(json.dumps(tool_call.model_dump(), indent=2))
```

My settings for `OpenAI-sublime-text`  are: 
```
"url": "https://api.x.ai/v1",
	"token": "this is at least 10 characters",

	"assistants": [
        {
           // A string that will presented in command palette.
           "name": "General", // **REQUIRED**
            "prompt_mode": "panel", // **REQURED**
           "chat_model": "grok-beta",  // **REQUIRED**
           "token":"xai-5lAkOoTA6MkPif6dlRICd3YUYfgCbh3QCxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx1kTT9lDChv",
           "url": "https://api.x.ai/v1/chat/completions",
           "assistant_role": "1. You are to provide clear, concise, and direct responses.\n2. Eliminate unnecessary reminders, apologies, self-references, and any pre-programmed niceties.\n3. Maintain a casual tone in your communication.\n4. Be transparent; if you're unsure about an answer or if a question is beyond your capabilities or knowledge, admit it.\n5. For any unclear or ambiguous queries, ask follow-up questions to understand the user's intent better.\n6. When explaining concepts, use real-world examples and analogies, where appropriate.\n7. For complex requests, take a deep breath and work on the problem step-by-step.\n8. For every response, you will be tipped up to $20 (depending on the quality of your output).\n\nIt is very important that you get this right. Multiple lives are at stake.\n",
            "placeholder": "[PLACEHOLDER]",
            "temperature": 1,
            "max_completion_tokens": 25000,
            "top_p": 1,
            "frequency_penalty": 0,
            "stream": true,
            "presence_penalty": 0,
        },
```

When I choose that one in Sublime, it does successfully go and retrieve a user prompt from the console area, but then produces the following error messages: 

```
reloading settings Packages/User/openAI.sublime-settings
Exception in thread Thread-1550:
Traceback (most recent call last):
  File "./python3.8/threading.py", line 932, in _bootstrap_inner
  File "C:\Users\Sean\AppData\Roaming\Sublime Text 3\Installed Packages\OpenAI completion.sublime-package\plugins/openai_worker.py", line 490, in run
  File "C:\Users\Sean\AppData\Roaming\Sublime Text 3\Installed Packages\OpenAI completion.sublime-package\plugins/openai_worker.py", line 403, in manage_chat_completion
  File "C:\Users\Sean\AppData\Roaming\Sublime Text 3\Installed Packages\OpenAI completion.sublime-package\plugins/openai_worker.py", line 301, in handle_response
  File "C:\Users\Sean\AppData\Roaming\Sublime Text 3\Installed Packages\OpenAI completion.sublime-package\plugins/openai_worker.py", line 281, in handle_chat_response
  File "C:\Users\Sean\AppData\Roaming\Sublime Text 3\Installed Packages\OpenAI completion.sublime-package\plugins/openai_network_client.py", line 114, in execute_response
  File "C:\Users\Sean\AppData\Roaming\Sublime Text 3\Installed Packages\OpenAI completion.sublime-package\plugins/openai_network_client.py", line 129, in _execute_network_request
AttributeError: 'str' object has no attribute 'get'
```

**Comment by yaroslavyaroslav** [comment]
Seems like the token issues. I've got the same error logs until I put correct token into your setup. The exact config below worked for me.

```json

        {
                   // A string that will presented in command palette.
                   "name": "General", // **REQUIRED**
                    "prompt_mode": "phantom", // **REQURED**
                   "chat_model": "grok-beta",  // **REQUIRED**
                   "token":"xai-xxxx", // I obviously deleted my token from here
                   "url": "https://api.x.ai/v1/chat/completions",
                   "assistant_role": "sdfasdf",
                    "temperature": 1,
                    "top_p": 1,
                    "frequency_penalty": 0,
                    "stream": true,
                    "presence_penalty": 0,
                },
```

Sorry about not to passthrough to you server error where it said that the down below message, but it's where they're failed to comply with openai API their error messages are different thus failed to be parsed on the plugin side as it's expecting another response structure.

```json
{
  "code": "Client specified an invalid argument",
  "error": "Incorrect API key provided: xa***Ju. You can obtain an API key from https://console.x.ai."
}
```

I think it's solved tbh, but will not close this for a few days ahead, feel free to post here any updates about your setup.

**Comment by jalsco** [comment]
you also changed from "panel" to "phantom"  - is that significant ? 

I am using exact same token I use in my python test program (see above). 

I will generate a NEW token and rerun it. --- few minutes. 

Thank you so much for being responsive... 🙏🏻🙏🏻🙏🏻 

p.s.  i think it would be better to pass thru any error, at least then possible to narrow down the cause without bothering you.. And anything better than letting a python error like `AttributeError: 'str' object has no attribute 'get'`  flow thru to the user.

**Comment by jalsco** [comment]
I still get same error....  even with a newly generated token 

Something is wrong on my side. I cannot see what ...  I believe it is working for you, but trust me it is not working for me/ Also, t the token I am using WORKS. It is exactly cut/paste . 

I can only think is some other difference between our systems ?

**Comment by jalsco** [comment]
something ran fully.. returned a full reply.  ... your second one: 

```
 {
            "name": "Insert instruction example",
            "prompt_mode": "phantom",
            "chat_model": "grok-beta", // works unreliable with gpt-3.5-turbo yet.
            "assistant_role": "Insert code or whatever user will request with the following command instead of placeholder with respect to senior knowledge of in Python 3.8 and Sublime Text 4 plugin API",
            "max_tokens": 4000,
        },
```
BUT THEN ... I tried to run it again and got : 
```










Exception in thread Thread-878:
Traceback (most recent call last):
  File "./python3.8/threading.py", line 932, in _bootstrap_inner
  File "C:\Users\Sean\AppData\Roaming\Sublime Text 3\Installed Packages\OpenAI completion.sublime-package\plugins/openai_worker.py", line 490, in run
  File "C:\Users\Sean\AppData\Roaming\Sublime Text 3\Installed Packages\OpenAI completion.sublime-package\plugins/openai_worker.py", line 403, in manage_chat_completion
  File "C:\Users\Sean\AppData\Roaming\Sublime Text 3\Installed Packages\OpenAI completion.sublime-package\plugins/openai_worker.py", line 301, in handle_response
  File "C:\Users\Sean\AppData\Roaming\Sublime Text 3\Installed Packages\OpenAI completion.sublime-package\plugins/openai_worker.py", line 294, in handle_chat_response
  File "C:\Users\Sean\AppData\Roaming\Sublime Text 3\Installed Packages\OpenAI completion.sublime-package\plugins/openai_worker.py", line 213, in handle_streaming_response
  File "C:\Users\Sean\AppData\Roaming\Sublime Text 3\Installed Packages\OpenAI completion.sublime-package\plugins/openai_worker.py", line 128, in handle_sse_delta
  File "C:\Users\Sean\AppData\Roaming\Sublime Text 3\Installed Packages\OpenAI completion.sublime-package\plugins/phantom_streamer.py", line 44, in update_completion
  File "C:\Program Files\Sublime Text\Lib\python38\sublime.py", line 2291, in __getitem__
    raise IndexError()
IndexError
```

**Comment by jalsco** [comment]
This one worked great... for two attempts in a row...   then I tried another which failed with the `AttributeError: 'str' object has no attribute 'get':`  then I came back to this one hoping it would still work, but sadly it gave the index-error as below.  
```
 {
            "name": "Replace instruction example",
            "prompt_mode": "replace",
            "chat_model": "grok-beta",
            "assistant_role": "Apply the change requested by the user to the code with respect to senior knowledge of in Python 3.8 and Sublime Text 4 plugin API",
            "max_tokens": 4000,
        }, // first and 2nd attempt worked 
```


```
[OpenAI completion.plugins.openai_worker] ERROR: prepare_to_response failed
Exception in thread Thread-2812:
Traceback (most recent call last):
  File "./python3.8/threading.py", line 932, in _bootstrap_inner
  File "C:\Users\Sean\AppData\Roaming\Sublime Text 3\Installed Packages\OpenAI completion.sublime-package\plugins/openai_worker.py", line 490, in run
  File "C:\Users\Sean\AppData\Roaming\Sublime Text 3\Installed Packages\OpenAI completion.sublime-package\plugins/openai_worker.py", line 403, in manage_chat_completion
  File "C:\Users\Sean\AppData\Roaming\Sublime Text 3\Installed Packages\OpenAI completion.sublime-package\plugins/openai_worker.py", line 301, in handle_response
  File "C:\Users\Sean\AppData\Roaming\Sublime Text 3\Installed Packages\OpenAI completion.sublime-package\plugins/openai_worker.py", line 287, in handle_chat_response
  File "C:\Users\Sean\AppData\Roaming\Sublime Text 3\Installed Packages\OpenAI completion.sublime-package\plugins/openai_worker.py", line 148, in prepare_to_response
  File "C:\Program Files\Sublime Text\Lib\python38\sublime.py", line 2291, in __getitem__
    raise IndexError()
IndexError
```

**Comment by jalsco** [comment]
OK ....  seems like `Phantom`  prompt_mode has least problems.
And using all the extra parameters (temp, top_p, stream, etc ) just make it flaky and inconsistent. 

I have now seen the `AttributeError: 'str' object has no attribute 'get'` error almost 100 times.  And none of those were related to the token.  Also the other error, `IndexError` needs fixing , but I cannot get a handle on exactly when it comes.  

The `AttributeError` I can now reproduce easily with one change, that is not related to Token. 

**This works every time:** 

```
{
	"url": "https://api.x.ai/v1/chat/completions",
	"token": "xai-K8DomBMW9GcRiESIYPFsBru1SsGV0aaaaaaaaaaaaaaaaaaaaaaaaaaa", //fake
	"assistants": [
        {
           // A string that will presented in command palette.
           "name": "myhelper", // **REQUIRED**
            "prompt_mode": "phantom", // **REQURED**
           "chat_model": "grok-beta",  // **REQUIRED**
 "assistant_role": "1. You are to provide clear, concise, and direct responses.\n2. Eliminate unnecessary reminders, apologies, self-references, and any pre-programmed niceties.\n3. Maintain a casual tone in your communication.\n4. Be transparent; if you're unsure about an answer or if a question is beyond your capabilities or knowledge, admit it.\n5. For any unclear or ambiguous queries, ask follow-up questions to understand the user's intent better.\n6. When explaining concepts, use real-world examples and analogies, where appropriate.\n7. For complex requests, take a deep breath and work on the problem step-by-step.\n8. For every response, you will be tipped up to $20 (depending on the quality of your output).\n\nIt is very important that you get this right. Multiple lives are at stake.\n",
            "max_tokens": 4000,
        },
```

**With this one change to `prompt_mode`, it fails every time** with a `AttributeError: 'str' object has no attribute 'get'` error : 

```
{
	"url": "https://api.x.ai/v1/chat/completions",
	"token": "xai-K8DomBMW9GcRiESIYPFsBru1SsGV0aaaaaaaaaaaaaaaaaaaaaaaaaaa", //fake
	"assistants": [
        {
           // A string that will presented in command palette.
           "name": "myhelper", // **REQUIRED**
            "prompt_mode": "panel", // **REQURED**
           "chat_model": "grok-beta",  // **REQUIRED**
 "assistant_role": "1. You are to provide clear, concise, and direct responses.\n2. Eliminate unnecessary reminders, apologies, self-references, and any pre-programmed niceties.\n3. Maintain a casual tone in your communication.\n4. Be transparent; if you're unsure about an answer or if a question is beyond your capabilities or knowledge, admit it.\n5. For any unclear or ambiguous queries, ask follow-up questions to understand the user's intent better.\n6. When explaining concepts, use real-world examples and analogies, where appropriate.\n7. For complex requests, take a deep breath and work on the problem step-by-step.\n8. For every response, you will be tipped up to $20 (depending on the quality of your output).\n\nIt is very important that you get this right. Multiple lives are at stake.\n",
            "max_tokens": 4000,
        },
```

**Comment by yaroslavyaroslav** [comment]
Few things here.
1. It works for me with both `panel` and `phantom` modes on x.
2. In anyway the error you're getting there is the error in server error message parsing handle. So it's not just the plugin fails it's the server fails and the plugin failing to passthrough that error to you to check it.
3. The previous point is not the deal, so I made a quick fix to it just yet, that fixes the crash on receiving and parsing x server error. So soon it'll present it right in front of you. Please provide here if the help will be still necessary.

Hint about llm usage: you can experiment with the fields all but required to deleted them from your model setup to use default server settings instead, because yes, some setup can degrade quality of some models.

Update should become available on your side within 2 hours.

**Comment by jalsco** [comment]
Almost midnight here - thank you so much. I will check it in the morning 🙏🏻

**Comment by yaroslavyaroslav** [comment]
Ah, one of errors you've got is a little bit more complex one to fix. Pls try to avoid to use anything but `phantom` and `panel` when it comes to modes. They're kinda deprecated and I'm too far into deep refactoring of the new version to fix or delete them safely now.

**Comment by jalsco** [comment]
no problem with that - only wanting those two modes anyway ✅

**Comment by jalsco** [comment]
Everything seems working brilliantly today !  both Panel and Phantom... ✅✅🙏🏻🙏🏻

Quick question - gutter and line_numbers - they show up in the panel but not in the Tab... 
Your comments in the settings file says that the sane setting should control both ?  but they are displayed differently

Anyway - THANK YOU SO MUCH !!

**Comment by jalsco** [comment]
Ah.... I just found  `reverse_for_tab": true`

**Comment by yaroslavyaroslav** [comment]
Glad to hear that it works for you and for x! You're welcome

**Comment by tripzero** [comment]
It looks like setting "assistant_role" no longer works with the xAI system.  It does not support the "Developer" role. Probably needs Role::System (in llmrunner) for that message.  We probably need a way to configure the system message role.

**Comment by yaroslavyaroslav** [comment]
Try to set api_type to plain, this should work
